services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: nexus123
      MYSQL_DATABASE: football
    ports:
      - '3336:3306'
    volumes:
      - 'database_data:/var/lib/mysql'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  mailcatcher:
    image: 'schickling/mailcatcher'
    container_name: cms_mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  database_test_data:
###< doctrine/doctrine-bundle ###
